spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

    # AdminClient가 NewTopic 빈을 보고 자동 생성
    admin:
      auto-create: true
      properties:
        security.protocol: ${spring.kafka.properties.security.protocol}
        sasl.mechanism: ${spring.kafka.properties.sasl.mechanism}
        sasl.jaas.config: ${spring.kafka.properties.sasl.jaas.config}
        sasl.client.callback.handler.class: ${spring.kafka.properties.sasl.client.callback.handler.class}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        compression.type: zstd
        linger.ms: 20
        batch.size: 131072
        enable.idempotence: true
        acks: all
        max.in.flight.requests.per.connection: 5

    consumer:
      group-id: backend-${spring.profiles.active}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        fetch.min.bytes: 65536         # 64KB
        fetch.max.wait.ms: 50

    listener:
      observation-enabled: true
    template:
      observation-enabled: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 0.05
  otlp:
    tracing:
      endpoint: http://otel-collector:4317